service: auth-api

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    RESEND_API_KEY: ${env:RESEND_API_KEY}
    PUBLIC_APP_URL: ${env:PUBLIC_APP_URL}

plugins:
  - serverless-offline

functions:
  register:
    handler: app/api/register/route.POST
    events:
      - http:
          path: api/register
          method: post

  verify:
    handler: app/api/verify/route.handler
    events:
      - http:
          path: api/verify
          method: get
          cors: true