services:
  postgres:
    image: ghcr.io/fboulnois/pg_uuidv7:1.6.0
    container_name: todo_container
    environment:
      POSTGRES_USER: todo_list_owner
      POSTGRES_PASSWORD: easypassword
      POSTGRES_DB: todo_list
    ports:
      - "5431:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - todo_network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    ports:
      - 4040:4040  # Expose ngrok's web interface
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH_TOKEN}
    command: ["tcp", "todo_container:5432"]
    depends_on:
      - postgres
    networks:
      - todo_network

networks:
  todo_network:
    name: todo_network

volumes:
  pg_data: